# syntax=docker/dockerfile:1

FROM eclipse-temurin:17-jdk-jammy
WORKDIR /code
ENV DB_URL=jdbc:postgresql://host.docker.internal:5436/
ENV DB_USERNAME=postgres
ENV DB_PASSWORD=pass
EXPOSE 7070
COPY Employee-Reimbursement-System.jar /home/Employee-Reimbursement-System.jar
CMD ["java","-jar","/home/Employee-Reimbursement-System.jar"]